### ISSUE TITLE
No way to take quizzes online

### ISSUE THREAD

**Issue by evaherrada** [dherrada/doctest_quizzes#8]

**Comment by evaherrada** [comment]
We (well, not me, but the person who's having me do this project) want these quizzes to be able to be taken online from a website. I do have a web server running NXINX that we could use for this, but a python framework would be preferable as the people who will be doing the bulk of the maintaining will be far more familiar with python frameworks, especially django

**Comment by evaherrada** [comment]
One thing that was suggested by mjsir911 was using telnet so it has a CLI but is online

**Comment by LindsayYoung** [comment]
Here is an interesting example of using jupyter notebooks for assigning and grading Python assignments https://nbgrader.readthedocs.io/en/stable/user_guide/highlights.html

Looks like there are some free hosting options https://blog.ouseful.info/2019/01/04/more-than-ten-free-hosted-jupyter-notebook-environments-you-can-try-right-now/

**Comment by LindsayYoung** [comment]
Ok, now I understand canvas is a requirement, looking to see if there is an API integration Reading up here: https://www.eduappcenter.com/apps/930#.XMs-zutKiRt 

This looks interesting, it's a "feemium" service
file:///Users/lindsayyoung/Downloads/Teaching%20Data%20Science%20with%20Jupyter,%20GitHub,%20and%20the%20Canvas%20LMS.pdf
